# Generated by Django 4.2.7 on 2025-08-29 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_requests', '0003_alter_insurancerequest_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('template_file', models.FileField(upload_to='summary_templates/', verbose_name='Файл шаблона')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон свода',
                'verbose_name_plural': 'Шаблоны сводов',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('collecting', 'Сбор предложений'), ('ready', 'Готов к отправке'), ('sent', 'Отправлен клиенту'), ('completed', 'Завершен')], default='collecting', max_length=20, verbose_name='Статус')),
                ('total_offers', models.IntegerField(default=0, verbose_name='Количество предложений')),
                ('best_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Лучшая премия')),
                ('best_company', models.CharField(blank=True, max_length=255, verbose_name='Лучшая компания')),
                ('summary_file', models.FileField(blank=True, null=True, upload_to='summaries/%Y/%m/%d/', verbose_name='Файл свода')),
                ('sent_to_client_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен клиенту')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email клиента')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='insurance_requests.insurancerequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Свод предложений',
                'verbose_name_plural': 'Своды предложений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Email компании')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('insurance_sum', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Страховая сумма')),
                ('insurance_premium', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Страховая премия')),
                ('franchise_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Размер франшизы')),
                ('installment_available', models.BooleanField(default=False, verbose_name='Рассрочка доступна')),
                ('installment_months', models.IntegerField(blank=True, null=True, verbose_name='Количество месяцев рассрочки')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Действительное предложение')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действительно до')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('original_email_subject', models.CharField(blank=True, max_length=255, verbose_name='Тема письма')),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='offers/%Y/%m/%d/', verbose_name='Файл предложения')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='summaries.insurancesummary', verbose_name='Свод')),
            ],
            options={
                'verbose_name': 'Предложение страховщика',
                'verbose_name_plural': 'Предложения страховщиков',
                'ordering': ['insurance_premium', '-received_at'],
                'unique_together': {('summary', 'company_name')},
            },
        ),
    ]
