# Generated by Django 4.2.7 on 2025-10-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insuranceoffer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='franchise_amount_variant1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Франшиза (вариант 1)'),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='franchise_amount_variant2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Франшиза (вариант 2)'),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='insurance_year',
            field=models.CharField(default='1 год', help_text='Например: "1 год", "2 год", "3 год"', max_length=10, verbose_name='Год страхования'),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='yearly_premium_with_franchise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Премия с франшизой'),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='yearly_premium_without_franchise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Премия без франшизы'),
        ),
        migrations.AlterField(
            model_name='insuranceoffer',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email компании'),
        ),
        migrations.AlterUniqueTogether(
            name='insuranceoffer',
            unique_together={('summary', 'company_name', 'insurance_year')},
        ),
    ]
