# Generated by Django 4.2.7 on 2025-10-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_add_yearly_offer_fields'),
    ]

    operations = [
        # Add new fields for the refactored model structure
        migrations.AddField(
            model_name='insuranceoffer',
            name='insurance_year_number',
            field=models.PositiveIntegerField(
                default=1,
                verbose_name='Номер года страхования',
                help_text='Числовое значение года страхования (1, 2, 3, ...)'
            ),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='franchise_1',
            field=models.DecimalField(
                max_digits=15,
                decimal_places=2,
                default=0,
                verbose_name='Франшиза-1',
                help_text='Размер первой франшизы (обычно 0)'
            ),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='premium_with_franchise_1',
            field=models.DecimalField(
                max_digits=15,
                decimal_places=2,
                null=True,
                blank=True,
                verbose_name='Премия с франшизой-1',
                help_text='Премия с первой франшизой'
            ),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='franchise_2',
            field=models.DecimalField(
                max_digits=15,
                decimal_places=2,
                null=True,
                blank=True,
                verbose_name='Франшиза-2',
                help_text='Размер второй франшизы (обычно больше 0)'
            ),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='premium_with_franchise_2',
            field=models.DecimalField(
                max_digits=15,
                decimal_places=2,
                null=True,
                blank=True,
                verbose_name='Премия с франшизой-2',
                help_text='Премия со второй франшизой'
            ),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='payments_per_year',
            field=models.PositiveIntegerField(
                default=1,
                verbose_name='Количество платежей в год',
                help_text='Количество платежей в год (1, 2, 3, 4, 12)'
            ),
        ),
    ]
