# Generated by Django 4.2.7 on 2025-10-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0004_migrate_existing_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceoffer',
            options={'ordering': ['premium_with_franchise_1', '-received_at'], 'verbose_name': 'Предложение страховщика', 'verbose_name_plural': 'Предложения страховщиков'},
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='franchise_amount',
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='franchise_amount_variant1',
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='franchise_amount_variant2',
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='installment_months',
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='insurance_premium',
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='insurance_year_number',
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='yearly_premium_with_franchise',
        ),
        migrations.RemoveField(
            model_name='insuranceoffer',
            name='yearly_premium_without_franchise',
        ),
        migrations.RemoveField(
            model_name='insurancesummary',
            name='client_email',
        ),
        migrations.AlterField(
            model_name='insuranceoffer',
            name='insurance_year',
            field=models.PositiveIntegerField(default=1, help_text='Числовое значение года страхования (1, 2, 3, ...)', verbose_name='Номер года страхования'),
        ),
    ]
