# Generated by Django 4.2.7 on 2025-10-13 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0005_remove_old_fields_and_rename_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancesummary',
            name='best_company',
        ),
        migrations.RemoveField(
            model_name='insurancesummary',
            name='best_premium',
        ),
    ]
