# Generated by Django 4.2.7 on 2025-10-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0006_remove_best_offer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceoffer',
            name='installment_variant_1',
            field=models.BooleanField(default=False, help_text='Доступна ли рассрочка для премии с франшизой-1', verbose_name='Рассрочка для варианта 1'),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='installment_variant_2',
            field=models.BooleanField(default=False, help_text='Доступна ли рассрочка для премии с франшизой-2', verbose_name='Рассрочка для варианта 2'),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='payments_per_year_variant_1',
            field=models.PositiveIntegerField(default=1, help_text='Количество платежей в год для варианта 1 (1, 2, 3, 4, 12)', verbose_name='Платежей в год (вариант 1)'),
        ),
        migrations.AddField(
            model_name='insuranceoffer',
            name='payments_per_year_variant_2',
            field=models.PositiveIntegerField(default=1, help_text='Количество платежей в год для варианта 2 (1, 2, 3, 4, 12)', verbose_name='Платежей в год (вариант 2)'),
        ),
    ]
