# Generated by Django 4.2.7 on 2025-10-21 19:42

from django.db import migrations, models


def update_completed_status_to_completed_accepted(apps, schema_editor):
    """
    Обновляет существующие записи со статусом 'completed' на 'completed_accepted'
    """
    InsuranceSummary = apps.get_model('summaries', 'InsuranceSummary')
    
    # Обновляем все записи со статусом 'completed' на 'completed_accepted'
    updated_count = InsuranceSummary.objects.filter(status='completed').update(status='completed_accepted')
    
    if updated_count > 0:
        print(f"Обновлено {updated_count} записей со статусом 'completed' на 'completed_accepted'")


def reverse_completed_status_update(apps, schema_editor):
    """
    Обратная операция: возвращает статус 'completed_accepted' обратно в 'completed'
    """
    InsuranceSummary = apps.get_model('summaries', 'InsuranceSummary')
    
    # Возвращаем статус обратно
    updated_count = InsuranceSummary.objects.filter(status='completed_accepted').update(status='completed')
    
    if updated_count > 0:
        print(f"Возвращено {updated_count} записей со статусом 'completed_accepted' на 'completed'")


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0007_add_installment_variants'),
    ]

    operations = [
        # Сначала обновляем данные
        migrations.RunPython(
            update_completed_status_to_completed_accepted,
            reverse_completed_status_update,
        ),
        # Затем изменяем поле модели
        migrations.AlterField(
            model_name='insurancesummary',
            name='status',
            field=models.CharField(choices=[('collecting', 'Сбор предложений'), ('ready', 'Готов к отправке'), ('sent', 'Отправлен в Альянс'), ('completed_accepted', 'Завершен: акцепт/распоряжение'), ('completed_rejected', 'Завершен: не будет')], default='collecting', max_length=20, verbose_name='Статус'),
        ),
    ]
