# Generated by Django 4.2.7 on 2025-10-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0009_standardize_company_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Уникальное название страховой компании', max_length=255, unique=True, verbose_name='Название компании')),
                ('display_name', models.CharField(help_text='Название для отображения в формах (может совпадать с основным названием)', max_length=255, verbose_name='Отображаемое название')),
                ('is_active', models.BooleanField(default=True, help_text='Доступна ли компания для выбора в формах', verbose_name='Активная')),
                ('is_other', models.BooleanField(default=False, help_text='Является ли это значением "другое" для нестандартных компаний', verbose_name='Значение "другое"')),
                ('sort_order', models.PositiveIntegerField(default=100, help_text='Порядок отображения в списках (меньшее значение = выше в списке)', verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Страховая компания',
                'verbose_name_plural': 'Страховые компании',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
