# Generated by Django 4.2.7 on 2025-10-22 20:55

from django.db import migrations


def populate_insurance_companies(apps, schema_editor):
    """Заполняет модель InsuranceCompany данными из константы INSURANCE_COMPANIES"""
    InsuranceCompany = apps.get_model('summaries', 'InsuranceCompany')
    
    # Список страховых компаний из constants.py
    companies_data = [
        ('Абсолют', 'Абсолют', 10),
        ('Альфа', 'Альфа', 20),
        ('ВСК', 'ВСК', 30),
        ('Согаз', 'Согаз', 40),
        ('РЕСО', 'РЕСО', 50),
        ('Ингосстрах', 'Ингосстрах', 60),
        ('Ренессанс', 'Ренессанс', 70),
        ('Росгосстрах', 'Росгосстрах', 80),
        ('Пари', 'Пари', 90),
        ('Совкомбанк СК', 'Совкомбанк СК', 100),
        ('Согласие', 'Согласие', 110),
        ('Энергогарант', 'Энергогарант', 120),
        ('ПСБ-страхование', 'ПСБ-страхование', 130),
        ('Зетта', 'Зетта', 140),
        ('другое', 'Другое', 1000),  # Специальное значение в конце списка
    ]
    
    created_count = 0
    for name, display_name, sort_order in companies_data:
        company, created = InsuranceCompany.objects.get_or_create(
            name=name,
            defaults={
                'display_name': display_name,
                'is_active': True,
                'is_other': (name == 'другое'),
                'sort_order': sort_order,
            }
        )
        if created:
            created_count += 1
    
    print(f"Создано {created_count} страховых компаний")


def reverse_populate_insurance_companies(apps, schema_editor):
    """Обратная миграция - удаляет все созданные компании"""
    InsuranceCompany = apps.get_model('summaries', 'InsuranceCompany')
    deleted_count = InsuranceCompany.objects.all().count()
    InsuranceCompany.objects.all().delete()
    print(f"Удалено {deleted_count} страховых компаний")


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0010_create_insurance_company_model'),
    ]

    operations = [
        migrations.RunPython(
            populate_insurance_companies,
            reverse_populate_insurance_companies
        ),
    ]
