# Generated by Django 4.2.7 on 2025-11-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0011_populate_insurance_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesummary',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительное примечание к своду', verbose_name='Примечание'),
        ),
    ]
