# Generated by Django 4.2.7 on 2025-11-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0012_insurancesummary_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceoffer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
    ]
