# Generated by Django 4.2.7 on 2025-12-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0013_alter_insuranceoffer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesummary',
            name='selected_company',
            field=models.CharField(blank=True, help_text='Страховая компания, выбранная при акцепте/распоряжении', max_length=255, null=True, verbose_name='Выбранная СК'),
        ),
    ]
