# Generated by Django 4.2.7 on 2026-04-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0014_add_selected_company_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesummary',
            name='selected_franchise_variant',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, 'Вариант 1 (Фр.-1 / СП-1)'), (2, 'Вариант 2 (Фр.-2 / СП-2)')],
                help_text='Выбранный вариант предложения (1 или 2) при акцепте/распоряжении',
                null=True,
                verbose_name='Выбранный вариант франшизы'
            ),
        ),
    ]
