# Generated by Django 4.2.7 on 2026-04-25 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('summaries', '0016_add_completed_at_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('from_status', models.CharField(blank=True, help_text='Пусто, если событие — создание объекта', max_length=32, verbose_name='Прошлый статус')),
                ('to_status', models.CharField(max_length=32, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Событие смены статуса',
                'verbose_name_plural': 'События смены статусов',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='insurancesummary',
            index=models.Index(fields=['status', 'completed_at'], name='summaries_i_status_f5009b_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancesummary',
            index=models.Index(fields=['sent_to_client_at'], name='summaries_i_sent_to_408244_idx'),
        ),
        migrations.AddField(
            model_name='statusevent',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил'),
        ),
        migrations.AddField(
            model_name='statusevent',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AddIndex(
            model_name='statusevent',
            index=models.Index(fields=['content_type', 'object_id', 'changed_at'], name='summaries_s_content_836f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='statusevent',
            index=models.Index(fields=['changed_at'], name='summaries_s_changed_ec0641_idx'),
        ),
        migrations.AddIndex(
            model_name='statusevent',
            index=models.Index(fields=['changed_by', 'changed_at'], name='summaries_s_changed_9004fe_idx'),
        ),
    ]
