# Generated by Codex on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0017_statusevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesummary',
            name='deal_summary_note',
            field=models.TextField(
                blank=True,
                help_text='Примечание, показываемое в резюме по сделке',
                verbose_name='Примечание к резюме',
            ),
        ),
    ]
