# Generated by Django 4.2.7 on 2026-09-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0020_insuranceoffer_legacy_coverage_territory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancesummary',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Фиксируется при переводе свода в статус "Завершен: акцепт/распоряжение" или "Завершен: не будет" (в том числе при автозакрытии)', null=True, verbose_name='Дата закрытия сделки'),
        ),
    ]
