# Generated by Django 4.2.7 on 2026-09-25 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summaries', '0021_completed_at_help_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата (МСК)')),
                ('logins_count', models.PositiveIntegerField(default=0, verbose_name='Входов')),
                ('page_views', models.PositiveIntegerField(default=0, help_text='GET-запросы пользователя', verbose_name='Просмотров страниц')),
                ('form_actions', models.PositiveIntegerField(default=0, help_text='POST/PUT/DELETE-запросы пользователя', verbose_name='Отправок форм')),
                ('crud_actions', models.PositiveIntegerField(default=0, help_text='Создания, изменения и удаления записей', verbose_name='Изменений данных')),
                ('crud_by_model', models.JSONField(blank=True, default=dict, help_text='{"insuranceoffer": {"create": 5, "update": 2, "delete": 0}, ...}', verbose_name='Изменения по типам записей')),
                ('sections', models.JSONField(blank=True, default=dict, help_text='Число запросов по разделам приложения', verbose_name='Разделы')),
                ('first_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Первое появление')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее появление')),
                ('sessions_count', models.PositiveIntegerField(default=0, verbose_name='Сессий')),
                ('active_minutes', models.PositiveIntegerField(default=0, help_text='Сумма сессий: события с разрывом не больше 30 минут, минимум 5 минут на сессию', verbose_name='Активных минут')),
                ('has_request_data', models.BooleanField(default=False, help_text='False — день собран только по входам и изменениям (просмотры страниц уже удалены из журнала)', verbose_name='Есть данные о просмотрах')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='Пересчитано')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Активность сотрудника за день',
                'verbose_name_plural': 'Активность сотрудников по дням',
                'ordering': ['-date', 'user'],
                'indexes': [models.Index(fields=['date'], name='summaries_u_date_47ef54_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userdailyactivity',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_daily_activity'),
        ),
    ]
