# Generated by Django 4.2.7 on 2026-09-26 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summaries', '0022_user_daily_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancesummary',
            name='company_statuses_required',
            field=models.BooleanField(default=False, help_text='Свод создан после запуска статусов СК: смена статуса свода требует статуса у каждой СК', verbose_name='Статусы СК обязательны'),
        ),
        migrations.CreateModel(
            name='SummaryCompanyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('undefined', 'Не определён'), ('not_requested', 'Не запрашивалась'), ('requested', 'Запрошена'), ('declined', 'Отказ'), ('offered', 'Предложение')], default='undefined', max_length=20, verbose_name='Статус')),
                ('status_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='Статус изменён')),
                ('restored', models.BooleanField(default=False, help_text='Статус восстановлен для старого свода по предложениям и примечанию (задача 2.5)', verbose_name='Восстановлен')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='summary_statuses', to='summaries.insurancecompany', verbose_name='Страховая компания')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_statuses', to='summaries.insurancesummary', verbose_name='Свод')),
            ],
            options={
                'verbose_name': 'Статус СК в своде',
                'verbose_name_plural': 'Статусы СК в сводах',
                'ordering': ['company__sort_order', 'company__name'],
                'indexes': [models.Index(fields=['company', 'status'], name='summaries_s_company_03cb34_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='summarycompanystatus',
            constraint=models.UniqueConstraint(fields=('summary', 'company'), name='unique_summary_company_status'),
        ),
    ]
