# Generated by Django 4.2.7 on 2026-09-27 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0023_summary_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='logo_code',
            field=models.CharField(blank=True, help_text='Имя файла логотипа в static/img/insurers/ без «.png» (например, alfa). Пусто — вместо логотипа показывается первая буква названия.', max_length=40, verbose_name='Код логотипа'),
        ),
    ]
