# Generated by Django 4.2.7 on 2026-10-07 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summaries', '0025_insurancecompany_logo_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurerResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Страховая компания')),
                ('template_version', models.PositiveSmallIntegerField(choices=[(1, 'Шаблон V1 или ручной ввод'), (2, 'Шаблон V2')], default=1, verbose_name='Версия шаблона ответа')),
                ('rnpk_status', models.CharField(blank=True, choices=[('included', 'Включены в полис'), ('not_included', 'Не включены'), ('approval', 'Требуется согласование')], default='', help_text='Для спецтехники и имущества', max_length=20, verbose_name='Риски РНПК')),
                ('rnpk_comment', models.TextField(blank=True, default='', verbose_name='Комментарий к рискам РНПК')),
                ('transport_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Если в заявке требуется перевозка', max_digits=15, null=True, verbose_name='Стоимость страхования перевозки, ₽')),
                ('transport_terms', models.TextField(blank=True, default='', verbose_name='Условия перевозки')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='responses/%Y/%m/%d/', verbose_name='Файл ответа')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurer_responses', to='summaries.insurancesummary', verbose_name='Свод')),
            ],
            options={
                'verbose_name': 'Ответ СК',
                'verbose_name_plural': 'Ответы СК',
                'ordering': ['summary_id', 'company_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='insurerresponse',
            constraint=models.UniqueConstraint(fields=('summary', 'company_name'), name='unique_summary_insurer_response'),
        ),
    ]
