# Generated by Django 4.2.7 on 2026-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0026_insurer_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurerresponse',
            name='rnpk_status',
            field=models.CharField(blank=True, choices=[('included', 'Будут прописаны в полисе'), ('not_included', 'Не будут прописаны в полисе')], default='', help_text='Для спецтехники и имущества', max_length=20, verbose_name='Риски РНПК'),
        ),
    ]
