# Generated by Django 4.2.7 on 2026-10-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0027_rnpk_two_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurerresponse',
            name='rnpk_comment',
        ),
        migrations.AddField(
            model_name='insurerresponse',
            name='inspection_status',
            field=models.CharField(blank=True, choices=[('not_required', 'Осмотр не требуется'), ('required', 'Требуется осмотр'), ('photo', 'Требуется осмотр, возможен осмотр по фотографиям')], default='', help_text='Ответ страховщика: нужен ли осмотр предмета лизинга', max_length=20, verbose_name='Осмотр'),
        ),
    ]
