# Generated by Django 4.2.7 on 2026-10-07 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0028_inspection_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurerresponse',
            name='inspection_status',
            field=models.CharField(blank=True, choices=[('not_required', 'Осмотр не требуется'), ('required', 'Требуется осмотр'), ('photo', 'Требуется осмотр (возможен по фотографиям)')], default='', help_text='Ответ страховщика: нужен ли осмотр предмета лизинга', max_length=20, verbose_name='Осмотр'),
        ),
    ]
