# Generated by Django 4.2.7 on 2025-08-29 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('uploaded', 'Загружена'), ('email_generated', 'Письмо сгенерировано'), ('email_sent', 'Письмо отправлено'), ('response_received', 'Получен ответ'), ('report_generated', 'Отчет сгенерирован'), ('completed', 'Завершена'), ('error', 'Ошибка')], default='uploaded', max_length=20, verbose_name='Статус')),
                ('client_name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН клиента')),
                ('insurance_type', models.CharField(default='КАСКО', max_length=100, verbose_name='Тип страхования')),
                ('insurance_period', models.IntegerField(verbose_name='Срок страхования (мес.)')),
                ('vehicle_info', models.TextField(blank=True, verbose_name='Информация о ТС')),
                ('has_franchise', models.BooleanField(default=False, verbose_name='Требуется франшиза')),
                ('has_installment', models.BooleanField(default=False, verbose_name='Требуется рассрочка')),
                ('has_autostart', models.BooleanField(default=False, verbose_name='Есть автозапуск')),
                ('response_deadline', models.DateTimeField(verbose_name='Срок ответа')),
                ('email_subject', models.CharField(blank=True, max_length=255, verbose_name='Тема письма')),
                ('email_body', models.TextField(blank=True, verbose_name='Текст письма')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Страховая заявка',
                'verbose_name_plural': 'Страховые заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Email компании')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата получения')),
                ('email_subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('email_body', models.TextField(verbose_name='Текст письма')),
                ('insurance_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Страховая сумма')),
                ('insurance_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Страховая премия')),
                ('parsed_data', models.JSONField(blank=True, default=dict, verbose_name='Распарсенные данные')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='insurance_requests.insurancerequest')),
            ],
            options={
                'verbose_name': 'Ответ страховой компании',
                'verbose_name_plural': 'Ответы страховых компаний',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ResponseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='response_attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_type', models.CharField(max_length=50, verbose_name='Тип файла')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='insurance_requests.insuranceresponse')),
            ],
            options={
                'verbose_name': 'Вложение к ответу',
                'verbose_name_plural': 'Вложения к ответам',
            },
        ),
        migrations.CreateModel(
            name='RequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Оригинальное имя файла')),
                ('file_type', models.CharField(max_length=50, verbose_name='Тип файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='insurance_requests.insurancerequest')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
    ]
