# Generated by Django 4.2.7 on 2025-08-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerequest',
            name='response_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок ответа'),
        ),
    ]
