# Generated by Django 4.2.7 on 2025-08-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0003_alter_insurancerequest_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerequest',
            name='insurance_period',
            field=models.CharField(max_length=200, verbose_name='Срок страхования'),
        ),
    ]
