# Generated by Django 4.2.7 on 2025-09-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0004_alter_insurancerequest_insurance_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='branch',
            field=models.CharField(blank=True, max_length=255, verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='dfa_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер ДФА'),
        ),
        migrations.AlterField(
            model_name='insurancerequest',
            name='vehicle_info',
            field=models.TextField(blank=True, verbose_name='Информация о предмете лизинга'),
        ),
    ]
