# Generated by Django 4.2.7 on 2025-09-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0005_insurancerequest_branch_insurancerequest_dfa_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала страхования'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='insurance_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания страхования'),
        ),
    ]
