# Generated by Django 4.2.7 on 2025-09-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0006_add_insurance_date_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerequest',
            name='insurance_type',
            field=models.CharField(choices=[('КАСКО', 'КАСКО'), ('страхование спецтехники', 'страхование спецтехники'), ('другое', 'другое')], default='КАСКО', max_length=100, verbose_name='Тип страхования'),
        ),
    ]
