# Generated by Django 4.2.7 on 2025-09-03 19:34

from django.db import migrations


def update_invalid_insurance_types(apps, schema_editor):
    """
    Обновляет существующие записи с некорректными типами страхования
    до одного из трех допустимых значений
    """
    InsuranceRequest = apps.get_model('insurance_requests', 'InsuranceRequest')
    
    # Допустимые типы страхования
    allowed_types = ['КАСКО', 'страхование спецтехники', 'другое']
    
    # Маппинг для преобразования некорректных типов
    type_mapping = {
        'ОСАГО': 'другое',
        'осаго': 'другое',
        'ОСГО': 'другое',
        'Страхование': 'другое',
        'страхование': 'другое',
        'Автострахование': 'КАСКО',
        'автострахование': 'КАСКО',
        'Спецтехника': 'страхование спецтехники',
        'спецтехника': 'страхование спецтехники',
    }
    
    # Получаем все записи с некорректными типами
    invalid_records = InsuranceRequest.objects.exclude(insurance_type__in=allowed_types)
    
    updated_count = 0
    for record in invalid_records:
        old_type = record.insurance_type
        
        # Пытаемся найти подходящий маппинг
        if old_type in type_mapping:
            new_type = type_mapping[old_type]
        else:
            # Если точного маппинга нет, используем "другое" по умолчанию
            new_type = 'другое'
        
        record.insurance_type = new_type
        record.save()
        updated_count += 1
        
        print(f'Updated record ID {record.id}: "{old_type}" -> "{new_type}"')
    
    print(f'Total updated records: {updated_count}')


def reverse_update_invalid_insurance_types(apps, schema_editor):
    """
    Обратная операция - в данном случае не реализуется,
    так как мы не можем восстановить оригинальные некорректные значения
    """
    print("Reverse migration not implemented - original invalid types cannot be restored")


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0007_add_insurance_type_choices'),
    ]

    operations = [
        migrations.RunPython(
            update_invalid_insurance_types,
            reverse_update_invalid_insurance_types,
        ),
    ]
