# Generated by Django 4.2.7 on 2025-09-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0008_update_invalid_insurance_types'),
    ]

    operations = [
        # Добавляем индексы для полей, используемых в поиске и фильтрации админки
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_requests_dfa_number ON insurance_requests_insurancerequest(dfa_number);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_requests_dfa_number;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_requests_client_name ON insurance_requests_insurancerequest(client_name);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_requests_client_name;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_requests_inn ON insurance_requests_insurancerequest(inn);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_requests_inn;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_requests_branch ON insurance_requests_insurancerequest(branch);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_requests_branch;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_requests_insurance_type ON insurance_requests_insurancerequest(insurance_type);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_requests_insurance_type;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_requests_status ON insurance_requests_insurancerequest(status);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_requests_status;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_requests_created_at ON insurance_requests_insurancerequest(created_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_requests_created_at;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_requests_response_deadline ON insurance_requests_insurancerequest(response_deadline);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_requests_response_deadline;"
        ),
        # Составной индекс для часто используемых комбинаций фильтров
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_requests_status_type ON insurance_requests_insurancerequest(status, insurance_type);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_requests_status_type;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_requests_branch_status ON insurance_requests_insurancerequest(branch, status);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_requests_branch_status;"
        ),
    ]
