# Generated by Django 4.2.7 on 2025-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerequest',
            name='insurance_type',
            field=models.CharField(choices=[('КАСКО', 'КАСКО'), ('страхование спецтехники', 'страхование спецтехники'), ('страхование имущества', 'страхование имущества'), ('другое', 'другое')], default='КАСКО', max_length=100, verbose_name='Тип страхования'),
        ),
    ]
