# Generated by Django 4.2.7 on 2025-09-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0010_add_property_insurance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='has_casco_ce',
            field=models.BooleanField(default=False, verbose_name='КАСКО кат. C/E'),
        ),
    ]
