# Generated by Django 4.2.7 on 2025-09-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0011_add_casco_ce_field'),
    ]

    operations = [
        # Add index on branch field for branch filtering
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_request_branch ON insurance_requests_insurancerequest(branch);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_request_branch;"
        ),
        
        # Add index on created_at field for date filtering
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_request_created_at ON insurance_requests_insurancerequest(created_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_request_created_at;"
        ),
        
        # Add composite index on branch and created_at for combined filtering
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS idx_insurance_request_branch_created_at ON insurance_requests_insurancerequest(branch, created_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_request_branch_created_at;"
        ),
    ]
