# Generated by Django 4.2.7 on 2025-09-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0013_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
    ]
