# Generated by Django 4.2.7 on 2025-10-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0014_add_notes_field'),
    ]

    operations = [
        # Add optimized index for DFA number pattern matching (LIKE/ICONTAINS operations)
        # SQLite version - creates a standard index that helps with pattern matching
        migrations.RunSQL(
            "CREATE INDEX idx_insurance_request_dfa_number_pattern ON insurance_requests_insurancerequest (dfa_number);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_request_dfa_number_pattern;"
        ),
        
        # Add composite index for DFA number pattern matching combined with branch filtering
        # This optimizes queries that filter by both DFA number and branch
        migrations.RunSQL(
            "CREATE INDEX idx_insurance_request_dfa_branch_pattern ON insurance_requests_insurancerequest (dfa_number, branch);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_request_dfa_branch_pattern;"
        ),
        
        # Add composite index for DFA number with created_at for date-based filtering
        # This optimizes queries that filter by DFA number and date ranges
        migrations.RunSQL(
            "CREATE INDEX idx_insurance_request_dfa_created_at ON insurance_requests_insurancerequest (dfa_number, created_at);",
            reverse_sql="DROP INDEX IF EXISTS idx_insurance_request_dfa_created_at;"
        ),
    ]
