# Generated by Django 4.2.7 on 2025-10-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0015_add_dfa_number_pattern_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancerequest',
            name='insurance_end_date',
        ),
        migrations.RemoveField(
            model_name='insurancerequest',
            name='insurance_start_date',
        ),
        migrations.AlterField(
            model_name='insurancerequest',
            name='insurance_period',
            field=models.CharField(blank=True, choices=[('1 год', '1 год'), ('на весь срок лизинга', 'на весь срок лизинга')], max_length=50, verbose_name='Срок страхования'),
        ),
    ]
