# Generated by Django 4.2.7 on 2025-10-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0016_remove_insurance_date_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='has_construction_work',
            field=models.BooleanField(default=False, verbose_name='Требуется СМР'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='has_transportation',
            field=models.BooleanField(default=False, verbose_name='Требуется перевозка'),
        ),
    ]
