# Generated by Django 4.2.7 on 2025-10-15 15:56

from django.db import migrations, models


def migrate_old_statuses(apps, schema_editor):
    """Миграция старых статусов к новым"""
    InsuranceRequest = apps.get_model('insurance_requests', 'InsuranceRequest')
    
    # Маппинг старых статусов к новым
    status_mapping = {
        'response_received': 'email_sent',
        'report_generated': 'completed',
        'error': 'uploaded',  # Сбрасываем ошибочные к начальному статусу
    }
    
    for old_status, new_status in status_mapping.items():
        updated_count = InsuranceRequest.objects.filter(status=old_status).update(status=new_status)
        if updated_count > 0:
            print(f"Migrated {updated_count} requests from '{old_status}' to '{new_status}'")


def reverse_migrate_statuses(apps, schema_editor):
    """Обратная миграция статусов (для отката)"""
    InsuranceRequest = apps.get_model('insurance_requests', 'InsuranceRequest')
    
    # Обратный маппинг (приблизительный, так как информация частично теряется)
    reverse_mapping = {
        'email_sent': 'response_received',  # Можно было бы быть 'email_sent' или 'response_received'
        'completed': 'report_generated',    # Можно было бы быть 'completed' или 'report_generated'
        'uploaded': 'error',               # Все ошибочные были сброшены к 'uploaded'
    }
    
    # Примечание: обратная миграция не может точно восстановить исходные статусы
    # так как несколько старых статусов могли быть объединены в один новый
    for new_status, old_status in reverse_mapping.items():
        updated_count = InsuranceRequest.objects.filter(status=new_status).update(status=old_status)
        if updated_count > 0:
            print(f"Reverse migrated {updated_count} requests from '{new_status}' to '{old_status}'")


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0017_add_transportation_construction_fields'),
    ]

    operations = [
        migrations.RunPython(migrate_old_statuses, reverse_migrate_statuses),
        migrations.AlterField(
            model_name='insurancerequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('uploaded', 'Загружена'),
                    ('email_generated', 'Письмо сгенерировано'),
                    ('email_sent', 'Письмо отправлено'),
                    ('completed', 'Завершена'),
                ],
                default='uploaded',
                max_length=20,
                verbose_name='Статус'
            ),
        ),
    ]
