# Generated by Django 4.2.7 on 2025-10-21 19:31

from django.db import migrations, models


def update_status_values(apps, schema_editor):
    """Обновляет существующие значения статусов в базе данных"""
    InsuranceRequest = apps.get_model('insurance_requests', 'InsuranceRequest')
    
    # Переименовываем email_sent в emails_sent
    InsuranceRequest.objects.filter(status='email_sent').update(status='emails_sent')
    
    # Обрабатываем записи со статусом 'completed' - переводим их в 'emails_sent'
    # так как это наиболее логичный предыдущий статус
    InsuranceRequest.objects.filter(status='completed').update(status='emails_sent')


def reverse_status_values(apps, schema_editor):
    """Откатывает изменения статусов (для обратной миграции)"""
    InsuranceRequest = apps.get_model('insurance_requests', 'InsuranceRequest')
    
    # Возвращаем emails_sent обратно в email_sent
    InsuranceRequest.objects.filter(status='emails_sent').update(status='email_sent')


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0018_auto_20251015_1856'),
    ]

    operations = [
        # Сначала обновляем данные
        migrations.RunPython(update_status_values, reverse_status_values),
        
        # Затем изменяем поле модели
        migrations.AlterField(
            model_name='insurancerequest',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Загружено'), ('email_generated', 'Письмо сгенерировано'), ('emails_sent', 'Письма отправлены')], default='uploaded', max_length=20, verbose_name='Статус'),
        ),
    ]
