# Generated by Django 4.2.7 on 2025-10-24 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0019_update_request_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='franchise_type',
            field=models.CharField(choices=[('none', 'Без франшизы'), ('with_franchise', 'Только с франшизой'), ('both_variants', 'Оба варианта')], default='none', max_length=20, verbose_name='Тип франшизы'),
        ),
    ]
