# Generated by Django 4.2.7 on 2025-10-27 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0021_migrate_franchise_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancerequest',
            name='email_sent_at',
        ),
    ]
