# Generated by Django 4.2.7 on 2025-10-27 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0022_remove_email_sent_at_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responseattachment',
            name='response',
        ),
        migrations.DeleteModel(
            name='InsuranceResponse',
        ),
        migrations.DeleteModel(
            name='ResponseAttachment',
        ),
    ]
