# Generated by Django 4.2.7 on 2025-10-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0023_remove_response_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='creditor_bank',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк-кредитор'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='key_completeness',
            field=models.CharField(blank=True, max_length=255, verbose_name='Комплектность ключей'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='pts_psm',
            field=models.CharField(blank=True, max_length=255, verbose_name='ПТС/ПСМ'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='telematics_complex',
            field=models.TextField(blank=True, verbose_name='Телематический комплекс'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='usage_purposes',
            field=models.TextField(blank=True, verbose_name='Цели использования'),
        ),
    ]
