# Generated by Django 4.2.7 on 2025-10-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0024_add_casco_additional_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='insurance_territory',
            field=models.TextField(blank=True, verbose_name='Территория страхования'),
        ),
    ]
