# Generated by Django 4.2.7 on 2025-11-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0025_add_insurance_territory_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='manufacturing_year',
            field=models.CharField(blank=True, max_length=255, verbose_name='Год выпуска'),
        ),
    ]
