# Generated by Django 4.2.7 on 2025-11-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0026_add_manufacturing_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='manager_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО Менеджера'),
        ),
    ]
