# Generated by Django 4.2.7 on 2025-12-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0027_insurancerequest_manager_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='deal_status',
            field=models.CharField(choices=[('new', 'Новая сделка'), ('prolongation', 'Пролонгация')], default='new', max_length=20, verbose_name='Статус сделки'),
        ),
    ]
