# Generated by Django 4.2.7 on 2026-04-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0028_insurancerequest_deal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='asset_status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Статус имущества'),
        ),
    ]
