# Generated by Django 4.2.7 on 2026-04-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0029_insurancerequest_asset_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='insurancerequest',
            index=models.Index(fields=['created_by', 'created_at'], name='insurance_r_created_58527f_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancerequest',
            index=models.Index(fields=['created_at'], name='insurance_r_created_fc5589_idx'),
        ),
    ]
