# Generated by Codex on 2026-05-12

from django.db import migrations


def preserve_manual_franchise_flags(apps, schema_editor):
    InsuranceRequest = apps.get_model('insurance_requests', 'InsuranceRequest')
    InsuranceRequest.objects.filter(
        has_franchise=True,
        franchise_type='none',
    ).update(franchise_type='with_franchise')


def restore_has_franchise_from_type(apps, schema_editor):
    InsuranceRequest = apps.get_model('insurance_requests', 'InsuranceRequest')
    InsuranceRequest.objects.filter(
        franchise_type__in=['with_franchise', 'both_variants'],
    ).update(has_franchise=True)
    InsuranceRequest.objects.filter(franchise_type='none').update(has_franchise=False)


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0030_insurancerequest_insurance_r_created_58527f_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            preserve_manual_franchise_flags,
            reverse_code=restore_has_franchise_from_type,
        ),
        migrations.RemoveField(
            model_name='insurancerequest',
            name='has_franchise',
        ),
    ]
