# Generated by Django 4.2.7 on 2026-05-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0031_remove_has_franchise'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='item_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Всего объектов в партии'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='item_no',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер объекта в партии'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='source_batch_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='Общий идентификатор партии для заявок, созданных из одного Excel-файла', null=True, verbose_name='ID партии'),
        ),
    ]
