# Generated by Django 4.2.7 on 2026-05-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0032_add_batch_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='acquisition_cost_currency',
            field=models.CharField(blank=True, choices=[('RUB', 'Рубли'), ('USD', 'Доллары США'), ('EUR', 'Евро')], max_length=3, null=True, verbose_name='Валюта стоимости'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='acquisition_cost_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Стоимость на момент приобретения'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='brand',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'Новое'), ('used', 'Б/у')], max_length=10, null=True, verbose_name='Состояние объекта'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='equipment_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип/категория техники'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='power_or_capacity',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Мощность/производительность'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='serial_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Заводской номер'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='vin',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='VIN'),
        ),
    ]
