# Generated by Django 4.2.7 on 2026-05-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0033_add_object_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancerequest',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='insurancerequest',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='insurancerequest',
            name='vin',
        ),
    ]
