# Generated by Django 4.2.7 on 2026-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0034_remove_vin_serial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения (для ИП)'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='business_activity',
            field=models.TextField(blank=True, null=True, verbose_name='Основной вид деятельности'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='postal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Почтовый адрес'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи заявки'),
        ),
    ]
