# Generated by Django 4.2.7 on 2026-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0035_add_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='guard_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия охраны/хранения'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='insured_party',
            field=models.CharField(blank=True, choices=[('lessor', 'Лизингодатель'), ('lessee', 'Лизингополучатель'), ('both', 'Оба')], max_length=10, null=True, verbose_name='Страхователь'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='insured_sum_type',
            field=models.CharField(blank=True, choices=[('aggregate', 'Агрегатная'), ('non_aggregate', 'Неагрегатная')], max_length=15, null=True, verbose_name='Тип страховой суммы'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='premium_frequency',
            field=models.CharField(blank=True, choices=[('single', 'Единовременно'), ('quarterly', 'Поквартально'), ('annual', 'Ежегодно')], max_length=10, null=True, verbose_name='Частота уплаты премии'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='property_location_right_holder',
            field=models.CharField(blank=True, choices=[('lessee_owner', 'Собственность лизингополучателя'), ('third_party_owner', 'Стороннее лицо')], help_text='Для страхования имущества', max_length=20, null=True, verbose_name='Правообладатель места расположения'),
        ),
    ]
