# Generated by Django 4.2.7 on 2026-05-21 18:49

from django.db import migrations, models


def clear_both_values(apps, schema_editor):
    InsuranceRequest = apps.get_model('insurance_requests', 'InsuranceRequest')
    InsuranceRequest.objects.filter(insured_party='both').update(insured_party=None)


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0036_add_deal_insurance_fields'),
    ]

    operations = [
        migrations.RunPython(clear_both_values, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='insurancerequest',
            name='insured_party',
            field=models.CharField(blank=True, choices=[('lessor', 'Лизингодатель'), ('lessee', 'Лизингополучатель')], max_length=10, null=True, verbose_name='Страхователь'),
        ),
    ]
