# Generated by Django 4.2.7 on 2026-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0037_remove_insured_party_both'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerequest',
            name='premium_frequency',
            field=models.CharField(blank=True, choices=[('single', 'Единовременно'), ('quarterly', 'Поквартально'), ('biannual', '2 раза в год'), ('annual', 'Ежегодно')], max_length=10, null=True, verbose_name='Частота уплаты премии'),
        ),
    ]
