# Generated by Django 4.2.7 on 2026-06-04 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0038_add_biannual_premium_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='source_object_count',
            field=models.PositiveIntegerField(default=1, help_text='Сколько полностью одинаковых строк объекта из исходной Excel-заявки представляет эта заявка', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество одинаковых объектов'),
        ),
    ]
