# Generated by Django 4.2.7 on 2026-06-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0039_insurancerequest_source_object_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='transportation_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок перевозки, дней'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='transportation_departure',
            field=models.CharField(blank=True, max_length=500, verbose_name='Пункт отправления (перевозка)'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='transportation_destination',
            field=models.CharField(blank=True, max_length=500, verbose_name='Пункт назначения (перевозка)'),
        ),
    ]
