# Generated by Django 4.2.7 on 2026-06-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0040_insurancerequest_transportation_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='manual_edits_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Сколько полей оператор изменил относительно распознанного из Excel', verbose_name='Ручных правок оператора'),
        ),
    ]
