# Generated by Django 4.2.7 on 2026-06-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0041_insurancerequest_manual_edits_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='parser_confidence',
            field=models.FloatField(blank=True, help_text='Уверенность распознавания парсером V2 на момент создания (0..1)', null=True, verbose_name='Уверенность парсера'),
        ),
        migrations.CreateModel(
            name='RequestFieldEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('common', 'Общее поле'), ('object', 'Поле объекта')], default='common', max_length=10, verbose_name='Область поля')),
                ('field_name', models.CharField(db_index=True, max_length=100, verbose_name='Поле')),
                ('field_label', models.CharField(max_length=255, verbose_name='Подпись поля')),
                ('original_value', models.TextField(blank=True, verbose_name='Распознано из Excel')),
                ('modified_value', models.TextField(blank=True, verbose_name='Внёс оператор')),
                ('edit_type', models.CharField(choices=[('filled', 'Дозаполнено'), ('cleared', 'Очищено'), ('changed', 'Исправлено')], db_index=True, default='changed', max_length=10, verbose_name='Тип правки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата правки')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_edits', to='insurance_requests.insurancerequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Ручная правка поля',
                'verbose_name_plural': 'Ручные правки полей',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['field_name', 'edit_type'], name='insurance_r_field_n_83e8ff_idx'), models.Index(fields=['created_at'], name='insurance_r_created_7d68de_idx')],
            },
        ),
    ]
