# Generated by Django 4.2.7 on 2026-06-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0042_insurancerequest_parser_confidence_requestfieldedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='object_description',
            field=models.TextField(blank=True, verbose_name='Описание объекта (исходное)'),
        ),
    ]
