# Generated by Django 4.2.7 on 2026-09-25 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_requests', '0043_insurancerequest_object_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfieldedit',
            name='edited_by',
            field=models.ForeignKey(blank=True, help_text='Заполняется для правок после создания; правки на входе делает автор заявки', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто правил'),
        ),
        migrations.AlterField(
            model_name='requestfieldedit',
            name='scope',
            field=models.CharField(choices=[('common', 'Общее поле'), ('object', 'Поле объекта'), ('post', 'После создания')], default='common', max_length=10, verbose_name='Область поля'),
        ),
    ]
