# Generated by Django 4.2.7 on 2026-09-27 14:18

from django.db import migrations, models

from insurance_requests.object_catalog import classify_request


def fill_object_catalog(apps, schema_editor):
    """Марка, класс и вид машины по справочнику техники для всех существующих заявок."""
    InsuranceRequest = apps.get_model('insurance_requests', 'InsuranceRequest')
    batch = []
    for insurance_request in InsuranceRequest.objects.all().iterator():
        info = classify_request(insurance_request)
        insurance_request.object_brand = info.brand
        insurance_request.object_class = info.object_class
        insurance_request.machine_kind = info.machine_kind
        batch.append(insurance_request)
    InsuranceRequest.objects.bulk_update(batch, ['object_brand', 'object_class', 'machine_kind'], batch_size=200)


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0044_request_field_edit_post_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='machine_kind',
            field=models.CharField(blank=True, default='', help_text='Для спецтехники: экскаватор, кран, каток и т. п. (справочник техники)', max_length=64, verbose_name='Вид машины'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='object_brand',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Марка по справочнику техники из описания объекта; пусто — марка не узнана', max_length=64, verbose_name='Марка (справочник)'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='object_class',
            field=models.CharField(blank=True, choices=[('passenger', 'Легковые'), ('lcv', 'Лёгкие коммерческие'), ('truck', 'Грузовые и тягачи'), ('trailer', 'Прицепы и полуприцепы'), ('bus', 'Автобусы'), ('special', 'Спецтехника'), ('equipment', 'Оборудование и имущество'), ('other', 'Прочее')], db_index=True, default='', help_text='Класс техники по справочнику: легковые, LCV, грузовые, прицепы, автобусы, спецтехника, имущество', max_length=16, verbose_name='Класс объекта'),
        ),
        migrations.RunPython(fill_object_catalog, migrations.RunPython.noop),
    ]
