# Generated by Django 4.2.7 on 2026-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0045_object_catalog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='franchise_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сумма в рублях или процент от страховой суммы — см. «Единица франшизы»', max_digits=14, null=True, verbose_name='Размер франшизы'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='franchise_unit',
            field=models.CharField(blank=True, choices=[('rub', 'руб.'), ('percent', '% от страховой суммы')], default='rub', max_length=10, verbose_name='Единица франшизы'),
        ),
    ]
