# Generated by Django 4.2.7 on 2026-10-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0045_object_catalog_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='franchise_amounts',
            field=models.JSONField(blank=True, default=list, help_text='Варианты размера франшизы (числа строками, например ["30000", "50000"]); единица — см. «Единица франшизы»', verbose_name='Размеры франшизы'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='franchise_unit',
            field=models.CharField(blank=True, choices=[('rub', 'руб.'), ('percent', '% от страховой суммы')], default='rub', max_length=10, verbose_name='Единица франшизы'),
        ),
    ]
