# Generated by Django 4.2.7 on 2026-10-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0047_backfill_franchise_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='lease_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания договора лизинга'),
        ),
        migrations.AddField(
            model_name='insurancerequest',
            name='lease_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала договора лизинга'),
        ),
    ]
