# Generated by Django 4.2.7 on 2026-10-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_requests', '0048_lease_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancerequest',
            name='anti_theft_systems',
            field=models.TextField(blank=True, help_text='Сигнализация, иммобилайзер, механические и спутниковые системы — из блока бланка «Противоугонные системы и оборудование»', verbose_name='Противоугонные системы'),
        ),
    ]
